name: linode_docker_test
services:
  nginx:
    container_name: linode_docker_test_nginx
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    # NO PORTS: docker network isolation - prevent direct external access.
    # Otherwise, if we expose it, we also got an infinite redirect loop from the proxy_pass of the main nginx.
    # ports:
    #   - 81:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./frontend:/var/www/html
    networks:
      internal_network:
        ipv4_address: 172.18.0.10

  api:
    container_name: linode_docker_test_api
    restart: always
    image: "oven/bun"
    volumes: ["./api:/home/bun/app"]
    entrypoint: []
    command: "/bin/sh -c 'NODE_ENV=production PORT=3000 bun index.js'"
    networks:
      internal_network:
        ipv4_address: 172.18.0.11

  frontend:
    container_name: linode_docker_test_api_frontend
    restart: always
    image: "oven/bun"
    volumes: ["./frontend:/home/bun/app"]
    entrypoint: []
    command: "/bin/sh -c 'PORT=5173 bun index.js'"
    networks:
      internal_network:
        ipv4_address: 172.18.0.12

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
